server:
  port: 8181
#Spring data sourcejpa.generate-ddl=true
spring:
  profiles:
    active: DEV
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: admin123
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    org:
      hibernate:
        sql: DEBUG