server:
  port: 8181

#Spring data source
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commerce
    username: postgres
    password: admin123
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org:
      hibernate:
        sql: DEBUG